apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: weather2acr.azurecr.io/weatherapp:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
